apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "be160f3a-xxxx-xxxx-xxxx-xxxxxxxxxxxx"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "aikv" # AI Foundry Access Token
    objects:  |
      array:
        - |
          objectName: webserver-config
          objectType: secret # object types: secret, key, or cert
        - |
          objectName: webserver-properties
          objectType: secret